//
// Created by kunal on 3/3/18.
//

#ifndef FOOTBALL_PENALTY_SHOOTER_CONSTANTS_H
#define FOOTBALL_PENALTY_SHOOTER_CONSTANTS_H


#define WIDTH 1920
#define HEIGHT 1080

#define WINDOW_NAME "Football Penalty Shooter"


#endif //FOOTBALL_PENALTY_SHOOTER_CONSTANTS_H
