//
// Created by kunal on 3/3/18.
//

#ifndef FOOTBALL_PENALTY_SHOOTER_CONSTANTS_H
#define FOOTBALL_PENALTY_SHOOTER_CONSTANTS_H


#define WIDTH 1920
#define HEIGHT 1080

#define WINDOW_NAME "Football Penalty Shooter"

#define BALL_RADIUS 0.2

#define THRESHOLD_ZERO 0.03
const long double PI = 3.141592653589793238L;


#endif //FOOTBALL_PENALTY_SHOOTER_CONSTANTS_H
